// Curated tourism overlay: famous travel cities/towns, keyed by ISO-3166 alpha-2.
// These are merged into the generated dataset and flagged as "gems" so they
// appear (and rank near the top) even when below the population threshold — a
// pure population cut would drop places like Hallstatt, Santorini or Queenstown.

export const CURATED_CITIES = {
  JP: ['Tokyo', 'Kyoto', 'Osaka', 'Hiroshima', 'Nara', 'Sapporo', 'Fukuoka', 'Nagoya', 'Kanazawa', 'Hakone', 'Nikko'],
  IT: ['Rome', 'Florence', 'Venice', 'Milan', 'Naples', 'Bologna', 'Turin', 'Verona', 'Amalfi', 'Siena', 'Palermo'],
  FR: ['Paris', 'Nice', 'Lyon', 'Marseille', 'Bordeaux', 'Strasbourg', 'Cannes', 'Toulouse', 'Annecy', 'Colmar'],
  ES: ['Barcelona', 'Madrid', 'Seville', 'Valencia', 'Granada', 'Malaga', 'Bilbao', 'San Sebastian', 'Cordoba', 'Toledo'],
  TH: ['Bangkok', 'Chiang Mai', 'Phuket', 'Krabi', 'Ayutthaya', 'Pai', 'Koh Samui', 'Chiang Rai', 'Sukhothai'],
  US: ['New York', 'Los Angeles', 'San Francisco', 'Chicago', 'Las Vegas', 'Miami', 'New Orleans', 'Seattle', 'Boston', 'Honolulu'],
  GB: ['London', 'Edinburgh', 'Bath', 'Oxford', 'Cambridge', 'Manchester', 'York', 'Liverpool', 'Glasgow', 'Bristol'],
  GR: ['Athens', 'Santorini', 'Mykonos', 'Thessaloniki', 'Heraklion', 'Rhodes', 'Corfu', 'Naxos', 'Delphi'],
  PT: ['Lisbon', 'Porto', 'Sintra', 'Faro', 'Funchal', 'Lagos', 'Coimbra', 'Evora'],
  ID: ['Bali', 'Denpasar', 'Jakarta', 'Yogyakarta', 'Ubud', 'Bandung', 'Surabaya'],
  VN: ['Hanoi', 'Ho Chi Minh City', 'Hoi An', 'Da Nang', 'Hue', 'Sapa', 'Nha Trang', 'Da Lat'],
  MX: ['Mexico City', 'Cancun', 'Tulum', 'Playa del Carmen', 'Oaxaca', 'Guadalajara', 'Puerto Vallarta', 'Merida'],
  AU: ['Sydney', 'Melbourne', 'Brisbane', 'Cairns', 'Perth', 'Gold Coast', 'Adelaide', 'Byron Bay', 'Hobart'],
  TR: ['Istanbul', 'Cappadocia', 'Antalya', 'Izmir', 'Bodrum', 'Pamukkale', 'Ankara'],
  DE: ['Berlin', 'Munich', 'Hamburg', 'Cologne', 'Frankfurt', 'Dresden', 'Heidelberg', 'Nuremberg'],
  NL: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Haarlem', 'Delft', 'Maastricht'],
  CH: ['Zurich', 'Geneva', 'Lucerne', 'Interlaken', 'Zermatt', 'Bern', 'Lausanne', 'Grindelwald'],
  IN: ['Delhi', 'Mumbai', 'Jaipur', 'Agra', 'Goa', 'Udaipur', 'Varanasi', 'Bengaluru', 'Rishikesh'],
  SG: ['Singapore'],
  KR: ['Seoul', 'Busan', 'Jeju', 'Gyeongju', 'Incheon', 'Jeonju'],
  AE: ['Dubai', 'Abu Dhabi', 'Sharjah'],
  MA: ['Marrakesh', 'Fez', 'Casablanca', 'Chefchaouen', 'Rabat', 'Essaouira'],
  HR: ['Dubrovnik', 'Split', 'Zagreb', 'Hvar', 'Zadar', 'Rovinj'],
  IS: ['Reykjavik', 'Vik', 'Akureyri', 'Selfoss', 'Hofn'],
  NZ: ['Auckland', 'Queenstown', 'Wellington', 'Christchurch', 'Rotorua', 'Wanaka', 'Napier'],
  EG: ['Cairo', 'Luxor', 'Aswan', 'Alexandria', 'Hurghada', 'Giza'],
  PE: ['Lima', 'Cusco', 'Arequipa', 'Puno', 'Iquitos'],
  BR: ['Rio de Janeiro', 'Sao Paulo', 'Salvador', 'Florianopolis', 'Manaus'],
  AR: ['Buenos Aires', 'Mendoza', 'Bariloche', 'Salta', 'Cordoba'],
  AT: ['Vienna', 'Salzburg', 'Innsbruck', 'Hallstatt', 'Graz'],
  BE: ['Brussels', 'Bruges', 'Ghent', 'Antwerp'],
  KH: ['Siem Reap', 'Phnom Penh', 'Sihanoukville', 'Battambang', 'Kampot'],
  CA: ['Toronto', 'Vancouver', 'Montreal', 'Quebec City', 'Banff', 'Ottawa', 'Victoria', 'Calgary'],
  CL: ['Santiago', 'Valparaiso', 'Puerto Varas', 'Punta Arenas'],
  CN: ['Beijing', 'Shanghai', 'Chongqing', "Xi'an", 'Chengdu', 'Guilin', 'Hangzhou', 'Suzhou', 'Guangzhou', 'Shenzhen'],
  CO: ['Bogota', 'Cartagena', 'Medellin', 'Cali', 'Santa Marta'],
  CR: ['San Jose', 'Liberia', 'Tamarindo'],
  CZ: ['Prague', 'Cesky Krumlov', 'Brno', 'Karlovy Vary'],
  DK: ['Copenhagen', 'Aarhus', 'Odense'],
  FI: ['Helsinki', 'Rovaniemi', 'Turku', 'Tampere'],
  HU: ['Budapest', 'Eger', 'Debrecen'],
  IE: ['Dublin', 'Galway', 'Cork', 'Killarney', 'Dingle'],
  IL: ['Jerusalem', 'Tel Aviv', 'Haifa', 'Eilat'],
  JO: ['Amman', 'Petra', 'Wadi Rum', 'Aqaba'],
  LA: ['Luang Prabang', 'Vientiane', 'Vang Vieng'],
  MY: ['Kuala Lumpur', 'George Town', 'Malacca', 'Langkawi', 'Kota Kinabalu'],
  MV: ['Male'],
  NP: ['Kathmandu', 'Pokhara'],
  NO: ['Oslo', 'Bergen', 'Tromso', 'Stavanger', 'Alesund'],
  PH: ['Manila', 'Cebu City', 'Puerto Princesa', 'Boracay', 'Tagbilaran', 'El Nido'],
  PL: ['Krakow', 'Warsaw', 'Gdansk', 'Wroclaw', 'Zakopane'],
  ZA: ['Cape Town', 'Johannesburg', 'Durban', 'Stellenbosch', 'Pretoria'],
  LK: ['Colombo', 'Kandy', 'Galle', 'Ella', 'Sigiriya'],
  SE: ['Stockholm', 'Gothenburg', 'Malmo', 'Kiruna'],
  TW: ['Taipei', 'Taichung', 'Tainan', 'Kaohsiung', 'Hualien'],
  KZ: ['Almaty', 'Astana', 'Shymkent'],
  UZ: ['Tashkent', 'Samarkand', 'Bukhara', 'Khiva'],
}
